#!/usr/bin/env bash
# shellcheck disable=SC2034
IMG_NAME="iot-pi"
RELEASE="bullseye"
LOCALE_DEFAULT="en_US.UTF-8"
TARGET_HOSTNAME="iot-pi"
KEYBOARD_KEYMAP="us"
TIMEZONE_DEFAULT="America/Phoenix"
FIRST_USER_NAME="pi"
FIRST_USER_PASS="password"
ENABLE_SSH=1
PUBKEY_SSH_FIRST_USER=0
STAGE_LIST="stage0 stage1 stage2 stage2-iot"

CLAIM_ID=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
