on: workflow_dispatch
name: Build Image
jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Stage 1 Image
        run: sudo chmod +x ./init.sh && sudo ./init.sh
