on:
  push:
  workflow_dispatch:
    inputs:
      compression:
        type: choice
        description: Compression Type (all level 6)
        default: zip
        options: [none, zip, gz, xz]
      compression_level:
        type: choice
        description: Compression Level (0-9)
        default: "6"
        options: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
name: Build Image with Pi-Gen
concurrency:
  group: pi-gen
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout this
        uses: actions/checkout@v3

      - name: Checkout pi-gen
        uses: actions/checkout@v3
        with:
          path: pi-gen
          repository: RPi-Distro/pi-gen
          ref: arm64

      - name: Set Build Configuration
        run: |
          sudo chmod +x ./.github/scripts/build-pigen.sh
          sudo ./.github/scripts/build-pigen.sh
