on: push
name: Build DietPi Image
concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get update -y
          chmod +x ./.github/scripts/build-dietpi.sh
          ./.github/scripts/build-dietpi.sh \
            ./dietpi/config.txt \
            ./dietpi/dietpi.txt \
            ./dietpi/post-boot.sh \
